# Generated by Django 6.0.6 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'password',
                    models.CharField(
                        db_column='contrasena_hash',
                        max_length=255,
                    ),
                ),
                (
                    'telefono',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    'rol',
                    models.CharField(
                        choices=[
                            ('CLIENTE', 'Cliente'),
                            ('RESTAURANTE', 'Restaurante'),
                            ('SUPERADMIN', 'Superadministrador'),
                        ],
                        default='CLIENTE',
                        max_length=20,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('ACTIVO', 'Activo'),
                            ('BLOQUEADO', 'Bloqueado'),
                        ],
                        default='ACTIVO',
                        max_length=12,
                    ),
                ),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['nombres', 'email'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
