# Generated by Django 6.0.6 on 2026-08-09

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                (
                    'telefono',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    'imagen_url',
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    'latitud',
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('-90')
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal('90')
                            ),
                        ],
                    ),
                ),
                (
                    'longitud',
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('-180')
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal('180')
                            ),
                        ],
                    ),
                ),
                (
                    'calificacion_promedio',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0')
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal('5')
                            ),
                        ],
                    ),
                ),
                (
                    'total_calificaciones',
                    models.PositiveIntegerField(default=0),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('ACTIVO', 'Activo'),
                            ('INACTIVO', 'Inactivo'),
                        ],
                        default='ACTIVO',
                        max_length=10,
                    ),
                ),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                (
                    'usuario_admin',
                    models.OneToOneField(
                        db_column='usuario_admin_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='restaurante_administrado',
                        to='reservas.usuario',
                    ),
                ),
            ],
            options={
                'db_table': 'restaurantes',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
