# Generated by Django 6.0.6 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_restaurante'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteCategoria',
            fields=[
                (
                    'pk',
                    models.CompositePrimaryKey(
                        'restaurante_id',
                        'categoria_id',
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurante_categoria',
                'ordering': ['restaurante_id', 'categoria_id'],
                'managed': False,
            },
        ),
    ]
