# Generated by Django 6.0.6 on 2026-08-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_restaurante_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRestaurante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'dia_semana',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Lunes'),
                            (2, 'Martes'),
                            (3, 'Miércoles'),
                            (4, 'Jueves'),
                            (5, 'Viernes'),
                            (6, 'Sábado'),
                            (7, 'Domingo'),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'horarios_restaurante',
                'ordering': ['restaurante_id', 'dia_semana'],
                'managed': False,
            },
        ),
    ]
