# Generated by Django 6.0.6 on 2026-08-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                (
                    'personas',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    'capacidad_mesa_solicitada',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('CONFIRMADA', 'Confirmada'),
                            ('CANCELADA', 'Cancelada'),
                            ('NO_SHOW', 'No show'),
                        ],
                        default='CONFIRMADA',
                        max_length=15,
                    ),
                ),
                (
                    'notas',
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-fecha', '-hora_inicio'],
                'managed': False,
            },
        ),
    ]
