# Generated by Django 6.0.6 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaMesa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('liberada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reserva_mesa',
                'ordering': ['reserva_id', 'mesa_id'],
                'managed': False,
            },
        ),
    ]
